version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py createsuperuserwithpassword --username ${ADMINISTRATOR_NAME} --password ${ADMINISTRATOR_PASSWORD} --email ${ADMINISTRATOR_MAILBOX} --preserve &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./db:/test_constructor/db
      - static:/test_constructor/src/static
    expose:
      - 8000
    env_file:
      - ./.env
  web:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static:/home/static
volumes:
  static: