version: '3.8'

services:
  db:
    image: nouchka/sqlite3
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - db:/test_constructor/db
  app:
    build: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py createsuperuserwithpassword --username ${ADMINISTRATOR_NAME} --password ${ADMINISTRATOR_PASSWORD} --email ${ADMINISTRATOR_EMAIL} --preserve &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - db:/test_constructor/db
    expose:
      - 8000
    env_file:
      - ./.env
  web:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db: